version: "1.0"
slug: "crypto_portfolio"
description: "Addon for managing crypto investments"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - config:rw
  - ssl
  - addons:rw
  - backup:rw
  - share:rw
options: {}
schema: {}
