name: "Crypto Portfolio"
version: "1.0"
slug: "crypto_portfolio"
description: "Addon for managing crypto investments"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: "application"
boot: "auto"
options:
  update_interval: "5min"
  currencies:
    - "bitcoin"
    - "ethereum"
    - "matic-network"
schema:
  update_interval: "str"
  currencies:
    - "str"
image: "local/\\crypto_portfolio:latest"
